# Generated by Django 6.0 on 2026-01-27 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_count', models.IntegerField(default=0)),
                ('used_count', models.IntegerField(default=0)),
                ('status_text', models.CharField(max_length=100)),
                ('details_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=50)),
                ('token_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Room', 'In Room'), ('Completed', 'Completed')], default='Waiting', max_length=20)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.doctor')),
            ],
        ),
    ]
