# Generated by Django 6.0 on 2026-01-27 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High (Critical)')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Room', 'In Room'), ('In Lab', 'In Lab'), ('In Radiology', 'In Radiology'), ('Completed', 'Completed')], default='Waiting', max_length=20),
        ),
    ]
