# Generated by Django 6.0 on 2026-01-29 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_appointment_priority_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(choices=[('09:00-10:00', '9:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 1:00 PM'), ('14:00-15:00', '2:00 PM - 3:00 PM'), ('15:00-16:00', '3:00 PM - 4:00 PM'), ('16:00-17:00', '4:00 PM - 5:00 PM'), ('17:00-18:00', '5:00 PM - 6:00 PM')], max_length=50),
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('xray', 'X-Ray'), ('blood_test', 'Blood Test'), ('mri', 'MRI Scan'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('urine_test', 'Urine Test'), ('biopsy', 'Biopsy'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
                ('report_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='backend_app.patientprofile')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate'), ('temperature', 'Temperature'), ('oxygen_level', 'Oxygen Level'), ('blood_sugar', 'Blood Sugar'), ('weight', 'Weight')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='backend_app.patientprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='backend_app.patientprofile'),
        ),
    ]
